version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glofox-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=glofox
      - DB_PASSWORD=glofox123
      - DB_NAME=glofox
      - DB_SSLMODE=disable

  postgres:
    image: postgres:14-alpine
    container_name: glofox-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=glofox
      - POSTGRES_PASSWORD=glofox123
      - POSTGRES_DB=glofox
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: